# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52cb39c8d704502fb17e4ac054dd4c211f00fbd913a7278cd65cac0a3c5d56c8675a6287d24a361ce119302acd9fc4f4d3cec14a292021751e917c8391e2b1d8

test:
  secret_key_base: 447f306ad6dbc6994201e3809b03cd8ea06986ade2af61cef1aab5411faade515de3081bc9149d51d79850fa1d0ccadad71720223452fc9e0d6257f63ced394b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
